-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Feb 15, 2021 at 02:33 PM
-- Server version: 10.4.11-MariaDB
-- PHP Version: 7.2.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `exam`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `Sr_No.` int(50) NOT NULL,
  `Username` varchar(50) NOT NULL,
  `Password` varchar(50) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`Sr_No.`, `Username`, `Password`) VALUES
(1, 'Amay', 'admin1'),
(2, 'Tushar1', 'admin2');

-- --------------------------------------------------------

--
-- Table structure for table `estque`
--

CREATE TABLE `estque` (
  `Question_ID` int(200) NOT NULL,
  `Question` varchar(1000) NOT NULL,
  `OptionA` varchar(1000) NOT NULL,
  `OptionB` varchar(1000) NOT NULL,
  `OptionC` varchar(1000) NOT NULL,
  `OptionD` varchar(1000) NOT NULL,
  `Answer` varchar(1000) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `estque`
--

INSERT INTO `estque` (`Question_ID`, `Question`, `OptionA`, `OptionB`, `OptionC`, `OptionD`, `Answer`) VALUES
(34, 'Which of the following is management option for air pollution?', 'Regulations and standards', 'Transport planning', 'Using CNG as fuel', 'All of these', '3'),
(12, 'The term ?Environment? has been derived from the French word which means to encircle or surround', 'Environ', 'Oikos', 'Geo', 'Aqua', '0'),
(13, 'Biosphere is', 'The solid shell of inorganic materials on the surface of the earth', 'The thin shell of organic matter on the surface of the earth comprising of all the living things', 'The sphere which occupies the maximum volume of all the spheres', 'All the above', '1'),
(14, 'Atmosphere consists of 79 percent Nitrogen and 21 percent Oxygen by', 'Volume', 'Weight', 'Density', 'All of these', '1'),
(15, 'The word ?Environment? is derived from', 'Greek', ' French', 'Spanish', 'English', '1'),
(16, 'Which among the following is a climatic factor?', 'pressure', 'humidity', 'temperature', 'all of the above', '3'),
(17, 'World environment day is on:', '5th May', '5th June', '18th July', '6th August', '1'),
(18, 'Sustainable development means', 'meeting present needs without compromising on future needs', 'progress of human beings', 'balance between human needs and the ability of earth to provide the resources', 'all of the above', '2'),
(19, 'The most important remedy to avoid negative impact due to industrialisation is', 'industry should be closed', 'don?t allow new industrial units', ' industry should treat all the wastes generated by it before disposal', 'industries should be shifted far away from human habitats', '2'),
(20, 'The adverse effect of modern agriculture is', 'Water pollution', 'Soil degradation', 'Water logging', 'All of the above', '1'),
(21, 'Soil erosion removes surface soil which contains', 'Organic matter', 'Plant nutrients', 'Both a and b', 'none of the above', '0'),
(22, 'Water logging is a phenomenon in which', 'Crop patterns are rotated', 'Soil root zone becomes saturated due to over irrigation', 'Erosion of soil', 'None of the above', '1'),
(23, 'Which of the following is the most environmental friendly agricultural practice?', 'Using chemical fertilizers', 'Using insecticides', 'Organic farming', 'None of the above', '2'),
(24, 'A herbivore is also known as a', 'Producer', 'First order consumer', 'Second order consumer.', 'Third order consumer', '1'),
(25, ' A product of photosynthesis is', 'Carbon dioxide', 'Water', 'Oxygen', 'Chlorophyll', '2'),
(26, 'Primary source of energy in a food web is/are', 'Green plants', 'Sun', 'Inorganic nutrients', 'Animals', '2'),
(27, 'A group of living organisms of the same kind living in the same place and at the same time refers to a', 'Community', 'Species', 'Population', 'Consumers', '2'),
(28, 'Which of the following can act as a pioneer species in a xerach succession', 'Lichens', 'Humans', 'Herbs', 'Animals', '0'),
(29, 'Energy flow in an ecosystem is', 'Bidirectional', ' Unidirectional', 'Multidirectional', 'All rounds', '2'),
(32, 'The term ‘Environment’ has been derived from the French word which means to encircle or surround', 'Environ', 'Oikos', 'Geo', 'Object', '0');

-- --------------------------------------------------------

--
-- Table structure for table `est_result`
--

CREATE TABLE `est_result` (
  `User_ID` int(200) NOT NULL,
  `First_Name` varchar(200) NOT NULL,
  `Middle_Name` varchar(200) NOT NULL,
  `Last_Name` varchar(200) NOT NULL,
  `Date` varchar(200) NOT NULL,
  `Time` varchar(200) NOT NULL,
  `Marks` varchar(200) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `est_result`
--

INSERT INTO `est_result` (`User_ID`, `First_Name`, `Middle_Name`, `Last_Name`, `Date`, `Time`, `Marks`) VALUES
(28, 'Tushar', 'Sunil', 'Rokade', '23/9/2020', '1:55 PM', '0'),
(29, 'Tushar', 'Sunil', 'Rokade', '23/9/2020', '2:53 PM', '0'),
(30, 'Tushar', 'Sunil', 'Rokade', '11/2/2021', '1:05 PM', '0');

-- --------------------------------------------------------

--
-- Table structure for table `etique`
--

CREATE TABLE `etique` (
  `Question_ID` int(100) NOT NULL,
  `Question` varchar(1000) NOT NULL,
  `OptionA` varchar(1000) NOT NULL,
  `OptionB` varchar(1000) NOT NULL,
  `OptionC` varchar(1000) NOT NULL,
  `OptionD` varchar(1000) NOT NULL,
  `Answer` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `etique`
--

INSERT INTO `etique` (`Question_ID`, `Question`, `OptionA`, `OptionB`, `OptionC`, `OptionD`, `Answer`) VALUES
(6810, '_________ allows us to control electronic components', 'RETful API', 'RESTful API', 'HTTP', 'MQTT', '0'),
(6811, 'MQTT stands for _____________', 'MQ Telemetry Things', 'MQ Transport Telemetry', 'MQ Transport Things', 'MQ Telemetry Transport', '3'),
(6812, 'PubNub publishes and subscribes _________ in order to send and receive messages.', ' Network', 'Account', 'Portal', 'Keys', '3'),
(6813, 'By clicking which key the PubNub will display public, subscribe, and secret keys.', ' Pane', 'Demo Keyset', 'Portal', 'Network', '1'),
(6814, 'The messageChannel class declares the _________ class attribute that defines the key string.', 'command_key', 'command-key', 'commandkey', 'Key_command', '0'),
(6815, '_________ method saves the received arguments in three attributes', '__Init', 'Init__', '__Init__', '_init_', '2'),
(6816, '_________ and _________ saves the publish and subscribe keys that we have generated with the PubNub Admin portal.', 'public_key and subscribe_key', 'Public-key and subscribe-key', ' publickey and subscribekey', 'Key_public and key_subscribe', '0'),
(6817, '_________ specifies the function that will be called when there is a new message received from the channel.', 'Reconnect', 'Error', 'Connect', 'Callback', '3'),
(6818, ' _________ specifies the function that will be called on an error event.', ' Callback', 'Error', 'Connect', 'Reconnect', '1'),
(6819, '_________ Specifies the function that will be called when a successful connection with the PubNub cloud.', 'Callback', 'Error', 'Connect', 'Reconnect', '3'),
(6820, 'IANA stands for:', 'Internal Assessment Numerical Access', 'Internet Association Numbers Authority', 'International Aid for Network Automation', 'Internet Assigned Numbers Authority', '3'),
(6821, 'Standard port number for secure MQTT is:', '1883', '8000', '8883', '8888', '2'),
(6822, 'Bluetooth 5.0 promises:', '4x Speed, 2x Range, 2x Data', '6x Speed, 3x Range, 3x Data', '2x Speed, 4x Range, 8x Data', '3x Speed, 4x Range, 8x Data', '2'),
(6823, 'Terms SSL and TLS stand for:', ' Secure Socket Layers and Transport Layer Session', ' Secure Socket Layers and Transport Layer Security', 'Secure Socket Layout and Transport Level Session', 'Session Socket Layers and Transport Layer Session', '1'),
(6824, 'Which one out of these is not a data link layer technology:', 'Bluetooth', 'UART', 'WiFi', 'HTTP', '3'),
(6825, 'Which layer is called a port layer in OSI model:', 'Session', 'Application', 'Presentation', 'Transport', '0'),
(6826, 'What is a firewall in computer networks:', 'A system designed to prevent unauthorized access', ' A web browser', 'The physical boundary of network', 'The Network Operating System', '0'),
(6827, 'Router operate at ............ layer of OSI reference model?', 'Layer 2 (Data Link)', ' Layer 3 (Network)', 'Layer 1 (Physical)', 'Layer 4 (Transport)', '1'),
(6828, 'Each IP packet must contain:', 'Only Destination IP Address', 'Only Source IP Address', 'None of Above', 'Source and destination IP Addresses', '3'),
(6829, 'Which one of this is not a networking device:', 'Router', 'Switch', 'Bridge', 'Traffic Analyzer', '3');

-- --------------------------------------------------------

--
-- Table structure for table `eti_result`
--

CREATE TABLE `eti_result` (
  `User_ID` int(200) NOT NULL,
  `First_Name` varchar(1000) NOT NULL,
  `Middle_Name` varchar(1000) NOT NULL,
  `Last_Name` varchar(1000) NOT NULL,
  `Date` varchar(1000) NOT NULL,
  `Time` varchar(1000) NOT NULL,
  `Marks` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `eti_result`
--

INSERT INTO `eti_result` (`User_ID`, `First_Name`, `Middle_Name`, `Last_Name`, `Date`, `Time`, `Marks`) VALUES
(11, 'Tushar', 'Sunil', 'Rokade', '11/2/2021', '1:12 PM', '0');

-- --------------------------------------------------------

--
-- Table structure for table `exam_detail`
--

CREATE TABLE `exam_detail` (
  `Subject` varchar(200) NOT NULL,
  `No_of_Question` varchar(50) NOT NULL,
  `Hours` varchar(200) NOT NULL,
  `Min` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `exam_detail`
--

INSERT INTO `exam_detail` (`Subject`, `No_of_Question`, `Hours`, `Min`) VALUES
('DBMS', '15', '00', '02'),
('SPOS', '12', '12', '12'),
('CN', '5', '01', '00');

-- --------------------------------------------------------

--
-- Table structure for table `feedback`
--

CREATE TABLE `feedback` (
  `Sr_No` int(11) NOT NULL,
  `Name` varchar(200) NOT NULL,
  `Enrollment_No` varchar(200) NOT NULL,
  `Mobile_No` varchar(200) NOT NULL,
  `Comment` varchar(200) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `management_result`
--

CREATE TABLE `management_result` (
  `User_ID` int(200) NOT NULL,
  `First_Name` varchar(200) NOT NULL,
  `Middle_Name` varchar(200) NOT NULL,
  `Last_Name` varchar(200) NOT NULL,
  `Date` varchar(200) NOT NULL,
  `Time` varchar(200) NOT NULL,
  `Marks` varchar(200) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

--
-- Table structure for table `managmentquestion`
--

CREATE TABLE `managmentquestion` (
  `Question_ID` int(200) NOT NULL,
  `Question` varchar(1000) NOT NULL,
  `OptionA` varchar(1000) NOT NULL,
  `OptionB` varchar(1000) NOT NULL,
  `OptionC` varchar(1000) NOT NULL,
  `OptionD` varchar(1000) NOT NULL,
  `Answer` varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `managmentquestion`
--

INSERT INTO `managmentquestion` (`Question_ID`, `Question`, `OptionA`, `OptionB`, `OptionC`, `OptionD`, `Answer`) VALUES
(641, 'Mc Gregor has given his contribution in_________', 'Concept of bureaucracy', 'Motion Study', 'Theory X and Theory Y', 'Time Study', '2'),
(642, 'Management is not___________ ', 'An economic resource', 'A system of authority', 'Team Activity', 'All are wrong', '3'),
(643, 'Management is __________', 'Methodology', 'Social Science', 'Team activity', 'All are correct', '3'),
(644, 'Meaning of _________is Right to command', 'Stability', 'Authority', 'Scalar chain', 'Initiative', '1'),
(645, 'Management is there form __________', 'After 1700', 'After 1800', 'After 1900', 'Historical period', '3'),
(646, 'Remuneration is not based _________', 'Performance', 'Responsibility', 'Emotions', 'Designation', '2'),
(647, 'Why plan Fails?', 'Lack of Knowledge', 'Insufficient data', 'Over Confidence', 'All are correct', '3'),
(648, 'Motion Study is associated with________', 'Adam smith', 'Frank', 'Gilberth', 'Maslow', '2'),
(649, 'Directing needs good _________in __________', 'Coordination,Control', 'Vision ,Leadership', 'Control ,Vision', 'None', '1'),
(650, 'Employee get energized due to _________', 'Motivation', 'Controlling', 'Decision making', 'Planning', '0'),
(651, 'Line Organization is of _________type', 'Horizontal', 'Vertical', 'Both', 'None', '1'),
(652, 'Line and Staff organization is ________', 'Vertical', 'Horizontal', 'Both (a)and (b)', 'None', '2'),
(653, 'Instructions is the _______ communication', 'Upward', 'Downward', 'Informal', 'Horizontal', '1'),
(654, 'Staff includes ________', 'Selection', 'Training', 'Promotion', 'All the above', '3'),
(655, '\'Request\'is the _______ Communication', 'Upward', 'Downward', 'Both(a)and(b)', 'None', '0'),
(656, 'Staffing deals with______', 'Manpower', 'Materials', 'Travelling Arrangement', 'Productions', '0'),
(657, 'Accident is ', 'Unfortunate', 'Mishappening', 'sudden', 'All of above', '3'),
(658, 'Fire drill is______', 'Drilling in fire', 'fire near drill', 'Demo of fire evacuation training', 'None', '2'),
(659, 'Work permit is Done at', 'High risks areas', 'Electric trouble shooting', 'Pressure  testing', 'All', '3'),
(660, 'Indian factory act pass in_______', '1935', '1947', '1948', '1976', '2');

-- --------------------------------------------------------

--
-- Table structure for table `student_reg`
--

CREATE TABLE `student_reg` (
  `User_ID` int(100) NOT NULL,
  `First_Name` varchar(200) NOT NULL,
  `Middle_Name` varchar(200) NOT NULL,
  `Last_Name` varchar(200) NOT NULL,
  `Mobile_No` varchar(200) NOT NULL,
  `Semester` varchar(200) NOT NULL,
  `Enrollment_No` varchar(200) NOT NULL,
  `Password` varchar(200) NOT NULL,
  `Student_status` varchar(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`Sr_No.`);

--
-- Indexes for table `estque`
--
ALTER TABLE `estque`
  ADD PRIMARY KEY (`Question_ID`);

--
-- Indexes for table `est_result`
--
ALTER TABLE `est_result`
  ADD PRIMARY KEY (`User_ID`);

--
-- Indexes for table `etique`
--
ALTER TABLE `etique`
  ADD PRIMARY KEY (`Question_ID`);

--
-- Indexes for table `eti_result`
--
ALTER TABLE `eti_result`
  ADD PRIMARY KEY (`User_ID`);

--
-- Indexes for table `feedback`
--
ALTER TABLE `feedback`
  ADD PRIMARY KEY (`Sr_No`);

--
-- Indexes for table `management_result`
--
ALTER TABLE `management_result`
  ADD PRIMARY KEY (`User_ID`);

--
-- Indexes for table `managmentquestion`
--
ALTER TABLE `managmentquestion`
  ADD PRIMARY KEY (`Question_ID`);

--
-- Indexes for table `student_reg`
--
ALTER TABLE `student_reg`
  ADD PRIMARY KEY (`User_ID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `Sr_No.` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `estque`
--
ALTER TABLE `estque`
  MODIFY `Question_ID` int(200) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=36;

--
-- AUTO_INCREMENT for table `est_result`
--
ALTER TABLE `est_result`
  MODIFY `User_ID` int(200) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=31;

--
-- AUTO_INCREMENT for table `etique`
--
ALTER TABLE `etique`
  MODIFY `Question_ID` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6832;

--
-- AUTO_INCREMENT for table `eti_result`
--
ALTER TABLE `eti_result`
  MODIFY `User_ID` int(200) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=12;

--
-- AUTO_INCREMENT for table `feedback`
--
ALTER TABLE `feedback`
  MODIFY `Sr_No` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `management_result`
--
ALTER TABLE `management_result`
  MODIFY `User_ID` int(200) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `managmentquestion`
--
ALTER TABLE `managmentquestion`
  MODIFY `Question_ID` int(200) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=662;

--
-- AUTO_INCREMENT for table `student_reg`
--
ALTER TABLE `student_reg`
  MODIFY `User_ID` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=68;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
